sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/ws-book975x65.tex

deploy:
  provider: releases
  file:
  - _build/ws-book975x65.pdf
  skip_cleanup: true
  on:
    tags: true

