sudo: required
dist: xenial
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-latex-recommended
script:
- latexmk -pdf ws-book975x65.tex
deploy:
  provider: releases
  api_key:
    secure: <key from travis CLI script>
  file:
  - ws-book975x65.pdf
  skip_cleanup: true
  on:
    tags: true

